parameters:
#    api_catalog.example.class: Api\CatalogBundle\Example

services:
#    api_catalog.example:
#        class: %api_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
