parameters:
#    catalog_order.example.class: Catalog\OrderBundle\Example

services:
#    catalog_order.example:
#        class: %catalog_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
