<?php

namespace Catalog\CategoryBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupParametersRepository extends EntityRepository
{
}
