<?php

namespace Catalog\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentSaleRepository extends EntityRepository
{
}
