generator: admingenerator.generator.doctrine
params:
    model: Catalog\FileGalleryBundle\Entity\File
    namespace_prefix: Catalog
    concurrency_lock: ~
    bundle_name: FileGalleryBundle
    pk_requirement: ~
    fields:
        file:
            dbType: string
            formType: file
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список файлов
            display: [ title, origin_name, is_active ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [ title, is_active, category]
    new:
        params:
            title: Новый файл
            tabs:
                Base: 
                    Base: [ is_active, file, category, title, description ]
                More:
                    More: [ sort ]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Редактировать файл \"%object%\"|{ %object%: File.title }|"
            tabs:
                Base: 
                    Base: [ is_active, file, category, title, description ]
                More:
                    More: [ sort ]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                delete: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: File.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
