parameters:
#    catalog_file_gallery.example.class: Catalog\FileGalleryBundle\Example

services:
#    catalog_file_gallery.example:
#        class: %catalog_file_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
