parameters:
#    catalog_project.example.class: Catalog\ProjectBundle\Example

services:
#    catalog_project.example:
#        class: %catalog_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
