parameters:
#    catalog_content.example.class: Catalog\ContentBundle\Example

services:
#    catalog_content.example:
#        class: %catalog_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
