parameters:
#    catalog_video_gallery.example.class: Catalog\VideoGalleryBundle\Example

services:
#    catalog_video_gallery.example:
#        class: %catalog_video_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
