parameters:
#    catalog_user.example.class: Catalog\UserBundle\Example

services:
    catalog_user.user_provider:
        class: Catalog\UserBundle\Security\UserProvider
        arguments: 
          - @fos_user.user_manager
