generator: admingenerator.generator.doctrine
params:
    model: Catalog\UserBundle\Entity\User
    namespace_prefix: Catalog
    concurrency_lock: ~
    bundle_name: UserBundle
    pk_requirement: ~
    fields:
        last_login:
            dbType: datetime
        plainPassword:
            dbType: string
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Список пользователей
            display: [ username, full_name, email, last_login, enabled]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:  [ username, email, enabled, roles]
    new:
        params:
            title: Новый пользователь
            tabs: 
                Base: 
                    Base: [ enabled, username, email, plainPassword ]
                Profile:
                    Profile: [ full_name, phone ]
                Projects:
                    Projects: [ projects ]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Редактировать пользователя \"%object%\"|{ %object%: User.username }|"
            tabs: 
                Base: 
                    Base: [ enabled, username, email, plainPassword ]
                Profile:
                    Profile: [ full_name, phone ]
                Projects:
                    Projects: [ projects ]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                delete: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: User.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
