<?php

namespace Catalog\CatalogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogProjectRepository extends EntityRepository
{
}
