<?php

namespace Catalog\ProjectBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFieldRepository extends EntityRepository
{
}
