<?php

namespace Catalog\OrderBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderContentRepository extends EntityRepository
{
}
