<?php

namespace Catalog\StockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockContentRepository extends EntityRepository
{
}
