generator: admingenerator.generator.doctrine
params:
    model: Catalog\CategoryBundle\Entity\Category
    namespace_prefix: Catalog
    concurrency_lock: ~
    bundle_name: CategoryBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: "Список категорий"
            display: [id, title, alias, is_active]
            actions:
                new: ~
            object_actions:
                move_up:
                    label:    Переместить вверх
                    icon:     icon-chevron-up
                    route:    Catalog_CategoryBundle_Category_move_up
                    params:
                        id: "{{Category.id}}"
                move_down:
                    label:    Переместить вниз
                    icon:     icon-chevron-down
                    route:    Catalog_CategoryBundle_Category_move_down
                    params:
                        id: "{{Category.id}}"
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: [title, alias, is_active]
    new:
        params:
            title: "Новая категория"
            tabs:
                Base:
                    Base: [ is_active, parent, title, alias, anons ]
                Groups:
                    Groups: [groups]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Редактировать категорию \"%object%\"|{ %object%: Category.title }|"
            tabs:
                Base:
                    Base: [ is_active, parent, title, alias, anons ]
                Groups:
                    Groups: [groups]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                delete: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Category.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
